---
environments:
  dev:
    docker:
      APP: backendtest
      VERSION: "0.4"
      registry: ecr
      url: 199920436475.dkr.ecr.us-east-1.amazonaws.com
      platforms: linux/amd64
      filename: Dockerfile
      filepath: .
      arguments:
        APP: "{{ APP }}"
        VERSION: "{{ VERSION }}"

    microservice:
      cluster: dev-ecs_cluster
      cpu: 128
      memory: 128
      expose_port: 3000
      replicas: 1
      domain_name: backendtest.dev.edeluquez.com
      variables:
        DATABASE: louvre
        USERNAME: admin
      secrets:
        PASSWORD: dev/db/fastapi/password
        ENDPOINT: dev/db/fastapi/endpoint
...
